export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';

export const REGISTER_USER_REQUEST_FAILED = 'REGISTER_USER_REQUEST_FAILED';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';

export const USER_SUCCESSFULLY_REGISTERED = 'USER_SUCCESSFULLY_REGISTERED';

export const USER_SUCCESSFULLY_LOGGED_IN = 'USER_SUCCESSFULLY_LOGGED_IN';

