export const CHECK_DEVICE_BLUETOOTH_STATE = 'CHECK_DEVICE_BLUETOOTH_STATE';  // should happen everytime user opens app

export const UPDATE_BLUETOOTH_STATE = 'UPDATE_BLUETOOTH_STATE';  // used to update bluetooth state to update UI accordingly

export const DEVICE_SCANED = 'DEVICE_SCANNED';

export const UPDATE_USER_SEARCHING_STATE = 'UPDATE_USER_SEARCHING_STATE';

export const SUCCESSFULLY_STARTED_BLUETOOTH_SEQ = 'SUCCESSFULLY_STARTED_BLUETOOTH_SEQ';

export const SUCCESSFULLY_STOPPED_BLUETOOTH_SEQ = 'SUCCESSFULLY_STOPPED_BLUETOOTH_SEQ';